version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - go-auth-api-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-auth-api
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - go-auth-api-network

volumes:
  mongo-data:

networks:
  go-auth-api-network: